[build-system]
requires = ["setuptools>=61.0"]
# build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "authorship"
version = "0.1.0"
description = "Authorship attribution and retrieval with retriever-reranker pipeline"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["authorship*"]
